### ISSUE TITLE
finding a suitable design

### ISSUE THREAD

**Issue by DaveSaah** [DaveSaah/file-system#2]
- Main program runs as a menu cli app. (Had most votes!)

#### Attributes
- creation_time
- modification_time
- file_type
- is_dir

> - A directory is also a file that has no content, but serves as a container for other files.
> - `is_dir` will track whether the current file is a directory or not.

#### Methods
- getters
- setters

#### Attributes
- root --> root of file system tree.

#### Methods
- createFile
- createDir
- deleteFile
- deleteDir
- moveFile
- moveDir
- search

> **New edits will be made as project progress...**

**Comment by DaveSaah** [comment]
### FileSystem Class
#### Methods
- showTree
- listDir

**Comment by TSTS09** [comment]
BBST 
- Folder class
- File class
- createFile 
- CreateFolder 
- ShowFolder
- deleteDir
- deleteFiles
- ShowFiles: Show all files in the current directory  
- moveFile
- moveDir
- search (PrimaryHash: in-built, SecondaryHash: in-built )

** Data structures **
- Stack (file path)
- BBST 
- Hashtables(folders)

**Comment by TSTS09** [comment]
** ewkjfhewu **

**Comment by TSTS09** [comment]
Some links 
- https://www.geeksforgeeks.org/treemap-in-java/
- https://www.geeksforgeeks.org/treemap-containsvalue-method-in-java-with-examples/?ref=lbp
- https://www.baeldung.com/java-treemap
